Allow for customization of escape key mapping
gennaro-tedesco/nvim-jqix pull request #16
Opened 2021-07-24 19:57 UTC by thedelchop

Allow the user of nvim-jqx to specify a key sequence that will close the
floating window.

2021-07-24 20:31 UTC, gennaro-tedesco requested changes
Thank you for your contribution: I have tested your branch and all works fine. I have made two small comments down below: other than that I believe we can merge.

2021-07-24 20:31 UTC, gennaro-tedesco commented on doc/jqx.txt
> +  lua require('nvim-jqx.config').close_window_mapping = ...
This should be in single quotes `lua require.... = ...`

2021-07-24 20:31 UTC, gennaro-tedesco commented on lua/nvim-jqx/config.lua
> +   close_window_mapping = close_window_mapping
probably `close_window_key` would be a more appropriate name, similar to `query_key`

2021-07-26 19:51 UTC, thedelchop commented
Ok @gennaro-tedesco I made the updates you requested, thanks for being so responsive!

2021-07-27 09:20 UTC, gennaro-tedesco approved these changes

2021-07-27 09:20 UTC, merged