Surround current file path with quotes
gennaro-tedesco/nvim-jqix pull request #17
Opened 2021-09-01 18:58 UTC by otherJL0

In order to work with Json files with spaces in their names, the `cur_file` variables are simply surrounded by quotes

2021-09-02 09:37 UTC, gennaro-tedesco commented
Good morning and thank you for your contribution!

While testing I have noticed that, once the quickfix list is populated with the file name surrounded by quotes, selecting the entry in the list and hitting `<CR>` does not bring the cursor to that line in the file, rather it generates an error (it opens a new empty buffer). This is probably due to the fact that the file name as per the `%` is unquoted, therefore still not recognised by vim. I suspect this happens [here](https://github.com/otherJL0/nvim-jqx/blob/1e59b77c1d4d01a5c2ecb50a8a78349e470bde1d/lua/nvim-jqx/jqx.lua#L55).

If I understand correctly your main change [of quotes](https://github.com/otherJL0/nvim-jqx/blob/1e59b77c1d4d01a5c2ecb50a8a78349e470bde1d/lua/nvim-jqx/jqx.lua#L30) is aimed to make sure that the keys are recognised as from a file with spaces: perhaps one could include `string.format([["%s"]]` only when fetching the keys and then leave the file name unquoted? Although I am not sure in that case the quickfix window will recognise the spaces either.

2021-09-02 09:39 UTC, gennaro-tedesco requested changes

2021-09-02 09:39 UTC, gennaro-tedesco commented on lua/nvim-jqx/jqx.lua
> +   local cur_file = string.format([["%s"]], vim.fn.getreg("%"))
Using this format as file name (with quotes) prevents the quickfix list to recognise the location in the file (because it does not recognise the file name with quotes to be the same as in the register `%`). I am not sure what the best solution is, here: probably only parsing the quotes when fetching the keys and leave the `local cur_file` variable intact?

2021-09-02 09:39 UTC, gennaro-tedesco commented on lua/nvim-jqx/jqx.lua
> +	  local json_types = {'string', 'number', 'vim.fn.getreg("%")boolean', 'array', 'object', 'null'}
What is the purpose of `vim.fn.getreg("%")` when getting the types?

2021-09-02 18:58 UTC, otherJL0 reviewed
So it seems that every instance where `jq` or `yq` is run the filename can be quoted, but as you mentioned the quoted filename is unfortunately not recognized by vim.

I've made a small update in the `jqx.lua`'s function `populate_qf` so that near the bottom the `qf_list` table's filenames are populated by calling the original `vim.fn.getreg("%")` which so far seems to work.

2021-09-02 18:58 UTC, otherJL0 commented on lua/nvim-jqx/jqx.lua
> +	  local json_types = {'string', 'number', 'vim.fn.getreg("%")boolean', 'array', 'object', 'null'}
Ah, that seems to be a mistake. Since it was a simple fix I tried to made the changes directly in Github. I think I just pasted the line there by mistake, will clean up.

2021-09-03 09:11 UTC, gennaro-tedesco commented
I am still getting errors when instead querying the content of the quickfix window via `X`, see [this line](https://github.com/gennaro-tedesco/nvim-jqx/blob/7aa18ba4c0ae75e7449680e16893c779e9adc821/lua/nvim-jqx/jqx.lua#L80); this is because now that the filename in the quickfix is unquoted, the `jq` query does not recognise the space. I understand it looks like a dog chasing its own tail (one piece of code breaks if quotes, the other breaks if no quotes, which is the reason why I omitted this case initially to start with, not sure it pays off the effort).

P. S. I am going to be off with limited computer access for the next days so I may be slower in responding to comments or reviews :)

2022-09-21 16:11 UTC, closed without merging